services:
  backend:
    build: backend
    image: e2e-automl-backend:latest     
    ports:
      - "8000:8000"
      - "54321:54321"
    volumes:
      - ./backend:/app/backend
    networks:
      - project_network

  frontend:
    build: frontend
    image: e2e-automl-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on: 
    - backend
    networks:
      - project_network

networks:
  project_network:
